// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSchool.DataAccess;

#nullable disable

namespace WebApiSchool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330115211_InitialAndCreateCorse")]
    partial class InitialAndCreateCorse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiSchool.Models.Course", b =>
                {
                    b.Property<Guid>("GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GUID");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            GUID = new Guid("bbaaffb1-6ae6-4886-bcda-15161b61e985"),
                            CourseName = "HCi",
                            Price = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
